version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 80:3000